# Generated by Django 4.0 on 2022-02-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsfromdatabaser',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carsfromdatabaser',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='carsfromdatabaser',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
